import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./ui/sidebar";
import Navbar from "./ui/navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="">
				<div className="xl:max-w-[1440px] relative mx-auto flex flex-row-reverse">
					<Sidebar />
					<div className="flex-1">
						<Navbar />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
